macro (add_source_group path)
    file(GLOB tmp ${path}/*.h ${path}/*.cpp)
    list(APPEND all_sources ${tmp} )
    if ("${path}" STREQUAL ".")
        set(src_src_grp  "Source Files")
    else ()
        set(src_src_grp  "Source Files/${path}")
    endif ()
    source_group("${src_src_grp}" FILES ${tmp})
endmacro()